# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
        npm install
        python3 -m venv .venv
        source .venv/bin/activate    
        pip3 install -r requirements.txt
        ./sync/sync.py
    command: netlify dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
